dist: trusty
sudo: false

language: node_js
node_js:
  - "8.10.0"

cache:
  directories:
    - node_modules

branches:
  only:
    - master
    - /^greenkeeper/.*$/

script:
  - yarn install
  - yarn test
  - yarn deploy
