dist: trusty
sudo: false

language: node_js
node_js:
  - "8.10.0"
  - "10"

cache:
  directories:
    - node_modules

branches:
  only:
    - master
    - develop
    - /^greenkeeper/.*$/

before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

script:
  - yarn install
  - yarn test
